version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
    - '5432:5432'
    networks:
    - postgres
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    networks:
    - postgres
    env_file: ../lrdf-idvisor-back/.env

networks:
  postgres:
  
