###########################################################################
# DEPLOY IMAGE
###########################################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
